version: '3.8'

services:
  api:
    build:
      context: .          # solution root
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - Redis__ConnectionString=redis:6379
    volumes:
      - ./logs:/app/logs
    depends_on:
      - redis
    networks:
      - gameoflife-network

  redis:
    container_name: aat-redis
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "8001:8001"                 
    volumes:
      - redis-data:/data
    networks:
      - gameoflife-network

volumes:
  redis-data:

networks:
  gameoflife-network:
    driver: bridge
